export const SET_ITEMS_BY_GUID = 'SET_ITEMS_BY_GUID'
export const SET_AGE_GROUPS = 'SET_AGE_GROUPS'
export const SET_SELECTED_AGE_GROUP = 'SET_SELECTED_AGE_GROUP'
export const SET_TRANSLATIONS = 'SET_TRANSLATIONS'

// User
export const SET_USER = 'SET_USER'
export const SET_USER_GROUPS = 'SET_USER_GROUPS'
export const SET_GROUP_MEMBER_TASK = 'SET_GROUP_MEMBER_TASK'

// Tasks
export const SET_TASKS = 'SET_TASKS'
export const DELETE_ACTIVE = 'DELETE_ACTIVE'

// Favourites
export const SET_FAVOURITES = 'SET_FAVOURITES'
export const DELETE_FAVOURITE = 'DELETE_FAVOURITE'
export const ADD_FAVOURITE = 'ADD_FAVOURITE'

// Notifications
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'
export const SET_NOTIFICATION = 'SET_NOTIFICATION'
export const MARK_NOTIFICATION_READ = 'MARK_NOTIFICATION_READ'
