export const ITEM_TYPES = {
  AGE_GROUP: 'AGE_GROUP',
  TASK_GROUP: 'TASK_GROUP',
  TASK: 'TASK',
}

export const COMPLETION_STATUS = {
  COMPLETED: 'COMPLETED',
  COMPLETION_REQUESTED: 'COMPLETION_REQUESTED',
  ARCHIVED: 'ARCHIVED',
  ACTIVE: 'ACTIVE',
}
